error.o: error.cc error.h
is-benchmark.o: is-benchmark.cc error.h timer.h is.h
is.o: is.cc is.h
pngio.o: pngio.cc pngio.h image.h error.h
pngsegment.o: pngsegment.cc pngio.h image.h error.h timer.h is.h
